services:
  # Frontend Service
  - type: web
    name: alta-ny-chatbot-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://alta-ny-chatbot-backend.onrender.com/api/:splat
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Service
  - type: web
    name: alta-ny-chatbot-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: altanewyork
      - key: RAPIDAPI_KEY
        sync: false
